/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTO.SanPhamDTO;
import java.awt.Color;
import static java.lang.Integer.*;

/**
 *
 * @author Locc
 */
public class Product extends javax.swing.JPanel {

    private SanPhamDTO sanPhamDTO;

//    private String ten;
//    private String gia;
    private Integer sl;

    private boolean isSelect;

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
    }

    public Product(SanPhamDTO sanPhamDTO) {
        initComponents();
        this.sanPhamDTO = new SanPhamDTO();
        this.sanPhamDTO = sanPhamDTO;
        this.sl = 1;
        jLabelTenSP.setText(sanPhamDTO.getTenSPString());
        jLabelSoLuong.setText(sl.toString());
        Integer tt = sanPhamDTO.getGiaInt() * sl;
        jLabelThanhTien.setText(tt.toString());
    }

//    public Product(String ten, String gia) {
//        initComponents();
//        this.ten = ten;
//        this.gia = gia;
//        this.sl = 1;
//
//        jLabelTenSP.setText(ten);
//        jLabelSoLuong.setText(sl.toString());
//        Integer tt = valueOf(gia) * sl;
//        jLabelThanhTien.setText(tt.toString());
//    }
    public void tangSoLuong() {
        sl++;
        jLabelSoLuong.setText(sl.toString());
        Integer tt = sanPhamDTO.getGiaInt() * sl;
        jLabelThanhTien.setText(tt.toString());
    }

    public void giamSoLuong() {
        sl--;
        jLabelSoLuong.setText(sl.toString());
    }

    public void updateSoLuong() {
        sl = Integer.valueOf(jLabelSoLuong.getText());
        Integer tt = sanPhamDTO.getGiaInt() * sl;
        jLabelThanhTien.setText(tt.toString());
    }

    public void resetSoLuong() {
        sl = 0;
        jLabelSoLuong.setText(sl.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTenSP = new javax.swing.JLabel();
        jLabelSoLuong = new javax.swing.JLabel();
        jLabelThanhTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(479, 60));
        setMinimumSize(new java.awt.Dimension(479, 60));
        setPreferredSize(new java.awt.Dimension(479, 60));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTenSP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTenSP.setText("Tên");
        jLabelTenSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTenSPMouseClicked(evt);
            }
        });
        add(jLabelTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 460, -1));

        jLabelSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSoLuong.setText("Số lượng:");
        jLabelSoLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSoLuongMouseClicked(evt);
            }
        });
        add(jLabelSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabelThanhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelThanhTien.setText("Tiền");
        jLabelThanhTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelThanhTienMouseClicked(evt);
            }
        });
        add(jLabelThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        requestFocus();
    }//GEN-LAST:event_formMouseClicked

    private void jLabelSoLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSoLuongMouseClicked
        isSelect = true;

    }//GEN-LAST:event_jLabelSoLuongMouseClicked

    private void jLabelTenSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTenSPMouseClicked
        // TODO add your handling code here:
        isSelect = true;

    }//GEN-LAST:event_jLabelTenSPMouseClicked

    private void jLabelThanhTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelThanhTienMouseClicked
        // TODO add your handling code here:
        isSelect = true;

    }//GEN-LAST:event_jLabelThanhTienMouseClicked

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        setBackground(Color.WHITE);
        isSelect = false;
    }//GEN-LAST:event_formFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        setBackground(new java.awt.Color(234, 105, 95));
        isSelect = true;
    }//GEN-LAST:event_formFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSoLuong;
    private javax.swing.JLabel jLabelTenSP;
    private javax.swing.JLabel jLabelThanhTien;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the sl
     */
    public Integer getSl() {
        return sl;
    }

    /**
     * @param sl the sl to set
     */
    public void setSl(Integer sl) {
        this.sl = sl;
    }

    /**
     * @return the jLabelSoLuong
     */
    public javax.swing.JLabel getjLabelSoLuong() {
        return jLabelSoLuong;
    }

    /**
     * @param jLabelSoLuong the jLabelSoLuong to set
     */
    public void setjLabelSoLuong(javax.swing.JLabel jLabelSoLuong) {
        this.jLabelSoLuong = jLabelSoLuong;
    }

    /**
     * @return the jLabelTenSP
     */
    public javax.swing.JLabel getjLabelTenSP() {
        return jLabelTenSP;
    }

    /**
     * @param jLabelTenSP the jLabelTenSP to set
     */
    public void setjLabelTenSP(javax.swing.JLabel jLabelTenSP) {
        this.jLabelTenSP = jLabelTenSP;
    }

    /**
     * @return the jLabelThanhTien
     */
    public javax.swing.JLabel getjLabelThanhTien() {
        return jLabelThanhTien;
    }

    /**
     * @param jLabelThanhTien the jLabelThanhTien to set
     */
    public void setjLabelThanhTien(javax.swing.JLabel jLabelThanhTien) {
        this.jLabelThanhTien = jLabelThanhTien;
    }

    /**
     * @return the isSelect
     */
    public boolean isSelect() {
        return isSelect;
    }

    /**
     * @param isSelect the isSelect to set
     */
    public void setSelect(boolean isSelect) {
        this.isSelect = isSelect;
    }

    /**
     * @return the sanPhamDTO
     */
    public SanPhamDTO getSanPhamDTO() {
        return sanPhamDTO;
    }

    /**
     * @param sanPhamDTO the sanPhamDTO to set
     */
    public void setSanPhamDTO(SanPhamDTO sanPhamDTO) {
        this.sanPhamDTO = sanPhamDTO;
    }
}
