/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.KhachHangBUS;
import DAO_Hibernate.KhachHangDAO;
import DAO_Hibernate.TestProcedure;
import DTO.KhachHangDTO;
import java.awt.Component;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Locc
 */
public class QLKhachHang extends javax.swing.JPanel {

    private KhachHangBUS khachHangBUS;
    private KhachHangDAO khachHangDAO;

    /**
     * Creates new form QLKhachHang
     */
    public QLKhachHang() {
        initComponents();
        jDialogAddKH.setLocationRelativeTo(this);
        jDialogDeleteKH.setLocationRelativeTo(this);
        khachHangBUS = new KhachHangBUS();
        for (int i = 0; i < khachHangBUS.getlist_KhachHangDTOs().size(); i++) {
            KhachHang khachHang = new KhachHang(khachHangBUS.getlist_KhachHangDTOs().get(i));
            jPanel4.add(khachHang);
        }
        jPanel4.revalidate();
        jPanel4.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDeleteKH = new javax.swing.JDialog();
        panelRound2 = new GUI.PanelRound();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDialogAddKH = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMaKH = new javax.swing.JTextField();
        jTextFieldTenKH = new javax.swing.JTextField();
        jTextFieldSDTKH = new javax.swing.JTextField();
        jPanelSave = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTenKH = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jLabelNgayDK = new javax.swing.JLabel();
        jLabelMaKH = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        panelRound3 = new GUI.PanelRound();
        jTextField6 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabelTenKH1 = new javax.swing.JLabel();
        jLabelSDT1 = new javax.swing.JLabel();
        jLabelNgayDK1 = new javax.swing.JLabel();
        jLabelMaKH1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();

        jDialogDeleteKH.setFocusable(false);
        jDialogDeleteKH.setFocusableWindowState(false);
        jDialogDeleteKH.setModal(true);
        jDialogDeleteKH.setUndecorated(true);
        jDialogDeleteKH.setResizable(false);
        jDialogDeleteKH.setSize(new java.awt.Dimension(625, 210));
        jDialogDeleteKH.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(143, 203, 253));
        panelRound2.setMaximumSize(new java.awt.Dimension(625, 210));
        panelRound2.setMinimumSize(new java.awt.Dimension(625, 210));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 22)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Xác nhận xóa khách hàng đã chọn?");
        panelRound2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 30, 610, -1));

        jLabel20.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 115, 130));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Lưu ý thông tin sẽ bị xoá hoàn toàn và không thể khôi phục");
        panelRound2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 80, 610, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 96, 151), 2));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.setFocusable(false);
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(45, 96, 151));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Hủy bỏ");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 5, 104, 32));

        panelRound2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 143, 170, 45));

        jLabel22.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 19)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Xác nhận");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.setFocusable(false);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        panelRound2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 104, 32));

        jDialogDeleteKH.getContentPane().add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 625, 210));

        jDialogAddKH.setMinimumSize(new java.awt.Dimension(420, 510));
        jDialogAddKH.setModal(true);
        jDialogAddKH.setUndecorated(true);
        jDialogAddKH.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(45, 96, 151));
        jPanel5.setMaximumSize(new java.awt.Dimension(420, 510));
        jPanel5.setMinimumSize(new java.awt.Dimension(420, 510));
        jPanel5.setPreferredSize(new java.awt.Dimension(420, 510));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(143, 203, 253));
        jPanel7.setMaximumSize(new java.awt.Dimension(420, 460));
        jPanel7.setMinimumSize(new java.awt.Dimension(420, 460));
        jPanel7.setPreferredSize(new java.awt.Dimension(420, 460));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 225, 219)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("Mã khách hàng");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 24));

        jLabel2.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel2.setText("Tên");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 24));

        jLabel3.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel3.setText("SĐT");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 24));

        jTextFieldMaKH.setEditable(false);
        jTextFieldMaKH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jTextFieldMaKH.setForeground(new java.awt.Color(151, 151, 151));
        jTextFieldMaKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel8.add(jTextFieldMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 240, 30));

        jTextFieldTenKH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jTextFieldTenKH.setForeground(new java.awt.Color(151, 151, 151));
        jTextFieldTenKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel8.add(jTextFieldTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, 240, 30));

        jTextFieldSDTKH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jTextFieldSDTKH.setForeground(new java.awt.Color(151, 151, 151));
        jTextFieldSDTKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel8.add(jTextFieldSDTKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 245, 240, 30));

        jPanelSave.setBackground(new java.awt.Color(45, 96, 151));
        jPanelSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSaveMouseClicked(evt);
            }
        });
        jPanelSave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lưu");
        jPanelSave.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, -10, 40, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/download.png"))); // NOI18N
        jPanelSave.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 8, 24, 24));

        jPanel8.add(jPanelSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 135, 41));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 450));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 420, 460));

        jLabel5.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thêm khách hàng");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 187, 60));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x.png"))); // NOI18N
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 13, 24, 24));

        jDialogAddKH.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 510));

        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(143, 203, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(143, 203, 253));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search 1.png"))); // NOI18N
        jPanel16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 21, 48, 48));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setMaximumSize(new java.awt.Dimension(330, 50));
        panelRound1.setMinimumSize(new java.awt.Dimension(330, 50));
        panelRound1.setPreferredSize(new java.awt.Dimension(330, 50));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setFont(new java.awt.Font("Be Vietnam Pro", 0, 24)); // NOI18N
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panelRound1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 280, 50));

        jPanel16.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 330, 50));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 430, 90));

        jPanel3.setBackground(new java.awt.Color(45, 96, 151));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Be Vietnam Pro Medium", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Xóa KH");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 10, 230, 70));

        jPanel6.setBackground(new java.awt.Color(45, 96, 151));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Be Vietnam Pro Medium", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thêm KH");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 70));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 10, 230, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jPanel2.setBackground(new java.awt.Color(45, 96, 151));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTenKH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelTenKH.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTenKH.setText("Tên");
        jPanel2.add(jLabelTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 190, 60));

        jLabelSDT.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelSDT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSDT.setText("SDT");
        jPanel2.add(jLabelSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 190, 60));

        jLabelNgayDK.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelNgayDK.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNgayDK.setText("Ngày đăng ký");
        jPanel2.add(jLabelNgayDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 170, 60));

        jLabelMaKH.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMaKH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelMaKH.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaKH.setText("Mã KH");
        jPanel2.add(jLabelMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 60));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 60));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel4);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1200, 750));

        jPanel9.setMaximumSize(new java.awt.Dimension(1200, 900));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(143, 203, 253));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(143, 203, 253));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search 1.png"))); // NOI18N
        jPanel17.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 21, 48, 48));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setMaximumSize(new java.awt.Dimension(330, 50));
        panelRound3.setMinimumSize(new java.awt.Dimension(330, 50));
        panelRound3.setPreferredSize(new java.awt.Dimension(330, 50));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setBorder(null);
        panelRound3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 280, 50));

        jPanel17.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 330, 50));

        jPanel10.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 430, 90));

        jPanel12.setBackground(new java.awt.Color(45, 96, 151));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Be Vietnam Pro Medium", 0, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Xóa KH");
        jPanel12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 70));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 10, 230, 70));

        jPanel13.setBackground(new java.awt.Color(45, 96, 151));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Be Vietnam Pro Medium", 0, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Thêm KH");
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 70));

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 10, 230, 70));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jPanel14.setBackground(new java.awt.Color(45, 96, 151));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTenKH1.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelTenKH1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTenKH1.setText("Tên");
        jPanel14.add(jLabelTenKH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 190, 60));

        jLabelSDT1.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelSDT1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSDT1.setText("SDT");
        jPanel14.add(jLabelSDT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 190, 60));

        jLabelNgayDK1.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelNgayDK1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNgayDK1.setText("Ngày đăng ký");
        jPanel14.add(jLabelNgayDK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 170, 60));

        jLabelMaKH1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMaKH1.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 24)); // NOI18N
        jLabelMaKH1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaKH1.setText("Mã KH");
        jPanel14.add(jLabelMaKH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 60));

        jPanel9.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 60));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(jPanel15);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1200, 750));

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
        jDialogDeleteKH.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        Component[] components = jPanel4.getComponents();

        // Iterate over the components in reverse order
        for (int i = components.length - 1; i >= 0; i--) {
            Component component = components[i];

            // Check if the component is an instance of Product
            if (component instanceof KhachHang) {
                KhachHang khachHang = (KhachHang) component;

                // Check if the customer needs to be deleted
                if (khachHang.isSelect()) {
                    // Remove the customer from Database
                    try {
                        if (khachHangBUS.xoa_proc(khachHang.getKhachHangDTO())) {
                            // Remove the customer from the panel and update the UI
                            jPanel4.remove(khachHang);
                            jPanel4.revalidate();
                            jPanel4.repaint();
                            System.out.println("Xoa KH thanh cong!");
                            jDialogDeleteKH.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Xóa KH không được!");
                        }
                    } catch (Exception e) {
                        // TODO Auto-generated catch block
                        // e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Lỗi ràng buộc khóa ngoại");
                        System.out.println("Lỗi ràng buộc khóa ngoại");
                    }
                }
            }
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        khachHangDAO = new KhachHangDAO();
        jTextFieldMaKH.setText(khachHangDAO.AutoGenerateMaKH());
        AbstractDocument doc = (AbstractDocument) jTextFieldSDTKH.getDocument();
        doc.setDocumentFilter(new LimitDigitsDocumentFilter(10));
        jDialogAddKH.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        jDialogAddKH.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jPanelSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSaveMouseClicked
        // TODO add your handling code here:
        KhachHangDTO khachHangDTO = new KhachHangDTO();
        khachHangDTO.setMaKHString(jTextFieldMaKH.getText());
        khachHangDTO.setTenKHString(jTextFieldTenKH.getText());
        khachHangDTO.setSDTKHString(jTextFieldSDTKH.getText());
        khachHangDTO.setNgayDangKyDate(new Date());

        khachHangDAO = new KhachHangDAO();
        try {
            if (khachHangDAO.insertKhachHang(khachHangDTO)) {
                jDialogAddKH.dispose();
                jPanel4.removeAll();
                KhachHangBUS khachHangBUS = new KhachHangBUS();
                for (int i = 0; i < khachHangBUS.getlist_KhachHangDTOs().size(); i++) {
                    KhachHang khachHang = new KhachHang(khachHangBUS.getlist_KhachHangDTOs().get(i));
                    jPanel4.add(khachHang);
                }
                jPanel4.revalidate();
                jPanel4.repaint();
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        } catch (SQLException ex) {
            if (ex.getErrorCode() == -20000) {
                // Bắt và xử lý lỗi do RAISE_APPLICATION_ERROR
                String errorMessage = ex.getMessage();
                JOptionPane.showMessageDialog(null, errorMessage);
                System.out.println("Lỗi từ cơ sở dữ liệu: " + errorMessage);
            } else {
                // Xử lý các lỗi khác
                ex.printStackTrace();
                Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jPanelSaveMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        jDialogDeleteKH.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField5.getText();
        TestProcedure testProcedure = new TestProcedure();
        jPanel4.removeAll();
        if (keyword.length() != 0) {
            List<KhachHangDTO> khachHangDTOs = testProcedure.SEARCH_KHACHHANG(keyword);
            if (!khachHangDTOs.isEmpty()) {
                for (KhachHangDTO khachHangDTO : khachHangDTOs) {
//                    Product_icon product_icon = new Product_icon(sanPhamDTO);
                    KhachHang khachHang = new KhachHang(khachHangDTO);
                    jPanel4.add(khachHang);
                }
            }
        } else {
            for (int i = 0; i < khachHangBUS.getlist_KhachHangDTOs().size(); i++) {
                KhachHang khachHang = new KhachHang(khachHangBUS.getlist_KhachHangDTOs().get(i));
                jPanel4.add(khachHang);
            }
        }
        jPanel4.revalidate();
        jPanel4.repaint();
    }//GEN-LAST:event_jTextField5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialogAddKH;
    private javax.swing.JDialog jDialogDeleteKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMaKH;
    private javax.swing.JLabel jLabelMaKH1;
    private javax.swing.JLabel jLabelNgayDK;
    private javax.swing.JLabel jLabelNgayDK1;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelSDT1;
    private javax.swing.JLabel jLabelTenKH;
    private javax.swing.JLabel jLabelTenKH1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldMaKH;
    private javax.swing.JTextField jTextFieldSDTKH;
    private javax.swing.JTextField jTextFieldTenKH;
    private GUI.PanelRound panelRound1;
    private GUI.PanelRound panelRound2;
    private GUI.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}
