/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.HQT_CSDL;

import GUI.*;
import DAO_Hibernate.KhachHangDAO;
import DTO.KhachHangDTO;

import static GUI.LoHang.formatter;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Locc
 */
public class KhachHang_HQT extends javax.swing.JPanel {

    private boolean isSelect;
    private KhachHangDTO khachHangDTO;

    private int clickCount;
    private long lastClickTime;

    /**
     * Creates new form KhachHang
     */
    public KhachHang_HQT() {
        initComponents();
    }

    public KhachHang_HQT(KhachHangDTO khachHangDTO) {
        initComponents();
        jDialogDetailKH.setLocationRelativeTo(this);
        this.khachHangDTO = new KhachHangDTO();
        this.khachHangDTO = khachHangDTO;
        jLabelMaKH.setText(khachHangDTO.getMaKHString());
        jLabelTenKH.setText(khachHangDTO.getTenKHString());
        jLabelSDT.setText(khachHangDTO.getSDTKHString());
        jLabelNgayDK.setText(formatter.format(khachHangDTO.getNgayDangKyDate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDetailKH = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldMaKH = new javax.swing.JTextField();
        jTextFieldTenKH = new javax.swing.JTextField();
        jPanelSave1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldSDTKH = new javax.swing.JTextField();
        jTextFieldNgayDK = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabelMaKH = new javax.swing.JLabel();
        jLabelTenKH = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jLabelNgayDK = new javax.swing.JLabel();

        jDialogDetailKH.setModal(true);
        jDialogDetailKH.setUndecorated(true);
        jDialogDetailKH.setSize(new java.awt.Dimension(420, 510));
        jDialogDetailKH.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(45, 96, 151));
        jPanel5.setMaximumSize(new java.awt.Dimension(420, 510));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(143, 203, 253));
        jPanel13.setMaximumSize(new java.awt.Dimension(420, 460));
        jPanel13.setMinimumSize(new java.awt.Dimension(420, 460));
        jPanel13.setPreferredSize(new java.awt.Dimension(420, 460));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 225, 219)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel26.setText("Mã khách hàng");
        jPanel14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 24));

        jLabel27.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel27.setText("Tên");
        jPanel14.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 24));

        jTextFieldMaKH.setEditable(false);
        jTextFieldMaKH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jTextFieldMaKH.setForeground(new java.awt.Color(151, 151, 151));
        jTextFieldMaKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jTextFieldMaKH.setEnabled(false);
        jPanel14.add(jTextFieldMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 240, 30));

        jTextFieldTenKH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jTextFieldTenKH.setForeground(new java.awt.Color(151, 151, 151));
        jTextFieldTenKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel14.add(jTextFieldTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, 240, 30));

        jPanelSave1.setBackground(new java.awt.Color(45, 96, 151));
        jPanelSave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSave1MouseClicked(evt);
            }
        });
        jPanelSave1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Lưu");
        jPanelSave1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, -10, 40, 60));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/download.png"))); // NOI18N
        jPanelSave1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 8, 24, 24));

        jPanel14.add(jPanelSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 135, 41));

        jLabel28.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel28.setText("SDT");
        jPanel14.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 24));

        jLabel33.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel33.setText("Ngày đăng ký");
        jPanel14.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, 24));

        jTextFieldSDTKH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jTextFieldSDTKH.setForeground(new java.awt.Color(151, 151, 151));
        jTextFieldSDTKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel14.add(jTextFieldSDTKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 245, 240, 30));

        jTextFieldNgayDK.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jTextFieldNgayDK.setForeground(new java.awt.Color(151, 151, 151));
        jTextFieldNgayDK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel14.add(jTextFieldNgayDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 335, 240, 30));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 450));

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 420, 460));

        jLabel31.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Thông tin Khách hàng");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 60));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x.png"))); // NOI18N
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 13, 24, 24));

        jDialogDetailKH.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 510));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(45, 96, 151)));
        setMaximumSize(new java.awt.Dimension(1200, 60));
        setPreferredSize(new java.awt.Dimension(1200, 60));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMaKH.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaKH.setText("Mã KH");
        jLabelMaKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaKHMouseClicked(evt);
            }
        });
        add(jLabelMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 60));

        jLabelTenKH.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelTenKH.setText("Tên");
        jLabelTenKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTenKHMouseClicked(evt);
            }
        });
        add(jLabelTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 330, 60));

        jLabelSDT.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelSDT.setText("SDT");
        jLabelSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSDTMouseClicked(evt);
            }
        });
        add(jLabelSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 180, 60));

        jLabelNgayDK.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelNgayDK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNgayDK.setText("NgayDK");
        jLabelNgayDK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNgayDKMouseClicked(evt);
            }
        });
        add(jLabelNgayDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 180, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelSave1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelSave1MouseClicked
        // TODO add your handling code here:
        KhachHangDTO khachHangDTO = new KhachHangDTO();
        khachHangDTO.setMaKHString(jTextFieldMaKH.getText());
        khachHangDTO.setSDTKHString(jTextFieldSDTKH.getText());
        khachHangDTO.setTenKHString(jTextFieldTenKH.getText());
        KhachHangDAO khachHangDAO = new KhachHangDAO();
        try {
            if (khachHangDAO.updateKhachHang(khachHangDTO)) {
                jDialogDetailKH.dispose();
                this.khachHangDTO = khachHangDTO;
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        } catch (SQLException ex) {
            if (ex.getErrorCode() == -20000) {
                // Bắt và xử lý lỗi do RAISE_APPLICATION_ERROR
                String errorMessage = ex.getMessage();
                JOptionPane.showMessageDialog(null, errorMessage);
                System.out.println("Lỗi từ cơ sở dữ liệu: " + errorMessage);
            } else {
                // Xử lý các lỗi khác
                ex.printStackTrace();
                Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }// GEN-LAST:event_jPanelSave1MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        jDialogDetailKH.dispose();
    }// GEN-LAST:event_jLabel32MouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        setBackground(new java.awt.Color(245, 181, 189));
        isSelect = true;
    }// GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        setBackground(Color.WHITE);
        isSelect = false;
    }// GEN-LAST:event_formFocusLost

    private void formMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        long currentTime = System.currentTimeMillis();

        if (clickCount == 1 && (currentTime - lastClickTime) <= 200) {
            // Xử lý sự kiện double click
            jTextFieldMaKH.setText(khachHangDTO.getMaKHString());
            jTextFieldTenKH.setText(khachHangDTO.gettenKHString());
            jTextFieldNgayDK.setText(formatter.format(khachHangDTO.getNgayDangKyDate()));
            jTextFieldSDTKH.setText(khachHangDTO.getSDTKHString());
            jDialogDetailKH.setVisible(true);
            // Reset lại số lần click và thời gian sau khi xử lý xong
            clickCount = 0;
            lastClickTime = 0;
        } else {
            // Lưu số lần click và thời gian hiện tại
            clickCount = 1;
            lastClickTime = currentTime;
            requestFocus();
        }

    }// GEN-LAST:event_formMouseClicked

    private void jLabelMaKHMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelMaKHMouseClicked
        // TODO add your handling code here:
        // isSelect = true;
        requestFocus();

    }// GEN-LAST:event_jLabelMaKHMouseClicked

    private void jLabelTenKHMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelTenKHMouseClicked
        // TODO add your handling code here:
        // isSelect = true;
        requestFocus();

    }// GEN-LAST:event_jLabelTenKHMouseClicked

    private void jLabelSDTMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelSDTMouseClicked
        // TODO add your handling code here:
        // isSelect = true;
        requestFocus();

    }// GEN-LAST:event_jLabelSDTMouseClicked

    private void jLabelNgayDKMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelNgayDKMouseClicked
        // TODO add your handling code here:
        // isSelect = true;
        requestFocus();

    }// GEN-LAST:event_jLabelNgayDKMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialogDetailKH;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabelMaKH;
    private javax.swing.JLabel jLabelNgayDK;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTenKH;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelSave1;
    private javax.swing.JTextField jTextFieldMaKH;
    private javax.swing.JTextField jTextFieldNgayDK;
    private javax.swing.JTextField jTextFieldSDTKH;
    private javax.swing.JTextField jTextFieldTenKH;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the isSelect
     */
    public boolean isSelect() {
        return isSelect;
    }

    /**
     * @param isSelect the isSelect to set
     */
    public void setSelect(boolean isSelect) {
        this.isSelect = isSelect;
    }

    /**
     * @return the khachHangDTO
     */
    public KhachHangDTO getKhachHangDTO() {
        return khachHangDTO;
    }

    /**
     * @param khachHangDTO the khachHangDTO to set
     */
    public void setKhachHangDTO(KhachHangDTO khachHangDTO) {
        this.khachHangDTO = khachHangDTO;
    }
}
