/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.HQT_CSDL;

import GUI.*;
import BUS.SanPhamBUS;
import DAO_Hibernate.ChiTietKhoDAO;
import DAO_Hibernate.SanPhamDAO;
import DTO.ChiTietKhoDTO;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import DTO.KhoDTO;
import DTO.SanPhamDTO;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Locc
 */
public class LoHang_HQT extends javax.swing.JPanel {

    public static final SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

    private KhoDTO khoDTO;
    private DefaultTableModel model;

    private ChiTietKhoDAO chiTietKhoDAO;
    private SanPhamDAO sanPhamDAO;

    private int clickCount;
    private long lastClickTime;

    private boolean isSelect;

    /**
     * Creates new form LoHang
     */
    public LoHang_HQT() {
        initComponents();
    }

    public LoHang_HQT(KhoDTO khoDTO) {
        initComponents();
        jDialogDetailLH.setLocationRelativeTo(null);
        jDialogAddSP_LH.setLocationRelativeTo(null);
        jDialogUpdateSP_LH.setLocationRelativeTo(null);
        this.khoDTO = new KhoDTO();
        this.khoDTO = khoDTO;

        jLabelMaLH.setText(khoDTO.getMaLoHangString());
        jLabelNgayNhap.setText(formatter.format(khoDTO.getNgayNhapDate()));
        jLabelSLSP.setText("1");
        jLabelMaNV.setText(khoDTO.getMaNhanVienString());
        jLabelSuplier.setText(khoDTO.getTenNhaCungCapString());

        AbstractDocument doc = (AbstractDocument) jTextField6.getDocument();
        doc.setDocumentFilter(new LimitDigitsDocumentFilter(4));

        model = (DefaultTableModel) jTable1.getModel();
    }

    public void hienthi(ResultSet rs) {
        Object obj[] = new Object[10];
        try {
            while (rs.next()) {
                obj[1] = rs.getString(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDetailLH = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelThemSP_LH = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanelXoaSP_LH = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelSuaSP_LH = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jDialogAddSP_LH = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanelSave = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldMaSP_LH = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextFieldMaLH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDialogUpdateSP_LH = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanelUpdate = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldMaSP_LH1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextFieldMaLH1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelMaLH = new javax.swing.JLabel();
        jLabelMaNV = new javax.swing.JLabel();
        jLabelNgayNhap = new javax.swing.JLabel();
        jLabelSuplier = new javax.swing.JLabel();
        jLabelSLSP = new javax.swing.JLabel();

        jDialogDetailLH.setFocusCycleRoot(false);
        jDialogDetailLH.setFocusable(false);
        jDialogDetailLH.setFocusableWindowState(false);
        jDialogDetailLH.setModal(true);
        jDialogDetailLH.setUndecorated(true);
        jDialogDetailLH.setResizable(false);
        jDialogDetailLH.setSize(new java.awt.Dimension(1200, 842));
        jDialogDetailLH.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(45, 96, 151));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(143, 203, 253));
        jPanel13.setMaximumSize(new java.awt.Dimension(1200, 791));
        jPanel13.setMinimumSize(new java.awt.Dimension(1200, 791));
        jPanel13.setPreferredSize(new java.awt.Dimension(1200, 791));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 202, 191)));
        jPanel14.setMaximumSize(new java.awt.Dimension(1168, 780));
        jPanel14.setMinimumSize(new java.awt.Dimension(1168, 780));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Phân loại", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel14.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1168, 730));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 61, 1168, 730));

        jPanelThemSP_LH.setBackground(new java.awt.Color(45, 96, 151));
        jPanelThemSP_LH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelThemSP_LH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelThemSP_LHMouseClicked(evt);
            }
        });
        jPanelThemSP_LH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thêm");
        jPanelThemSP_LH.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, 50));

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon _edit pencil_.png"))); // NOI18N
        jPanelThemSP_LH.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, 19));

        jPanel13.add(jPanelThemSP_LH, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 5, 150, 50));

        jPanelXoaSP_LH.setBackground(new java.awt.Color(45, 96, 151));
        jPanelXoaSP_LH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelXoaSP_LH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelXoaSP_LHMouseClicked(evt);
            }
        });
        jPanelXoaSP_LH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Xóa");
        jPanelXoaSP_LH.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jPanel13.add(jPanelXoaSP_LH, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 5, 150, 50));

        jPanelSuaSP_LH.setBackground(new java.awt.Color(45, 96, 151));
        jPanelSuaSP_LH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelSuaSP_LH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSuaSP_LHMouseClicked(evt);
            }
        });
        jPanelSuaSP_LH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sửa");
        jPanelSuaSP_LH.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jPanel13.add(jPanelSuaSP_LH, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 5, 150, 50));

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 1200, 791));

        jLabel26.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Chi tiết lô hàng");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 60));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x.png"))); // NOI18N
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 13, -1, -1));

        jDialogDetailLH.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 842));

        jDialogAddSP_LH.setModal(true);
        jDialogAddSP_LH.setUndecorated(true);
        jDialogAddSP_LH.setResizable(false);
        jDialogAddSP_LH.setSize(new java.awt.Dimension(420, 570));
        jDialogAddSP_LH.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(45, 96, 151));
        jPanel6.setMaximumSize(new java.awt.Dimension(420, 568));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(143, 203, 253));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 202, 191)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSave.setBackground(new java.awt.Color(45, 96, 151));
        jPanelSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSaveMouseClicked(evt);
            }
        });
        jPanelSave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lưu");
        jPanelSave.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, -10, 40, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/download.png"))); // NOI18N
        jPanelSave.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 8, 24, 24));

        jPanel8.add(jPanelSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 452, 135, 41));

        jLabel8.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel8.setText("Giá");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, 135, 24));

        jLabel9.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel9.setText("Mã sản phẩm");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 135, 24));

        jLabel10.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel10.setText("Mô tả");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 156, 135, 24));

        jLabel12.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel12.setText("Tên sản phẩm");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 22, 135, 24));

        jLabel13.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel13.setText("Phân loại");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 87, 135, 24));

        jLabel14.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel14.setText("Số lượng");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 156, 135, 24));

        jTextFieldMaSP_LH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextFieldMaSP_LH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jTextFieldMaSP_LH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaSP_LHActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldMaSP_LH, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, 135, 24));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField2.setText("0");
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel8.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 111, 135, 24));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel8.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 180, 135, 24));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 46, 135, 24));

        jTextField6.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField6.setText("0");
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 180, 135, 24));

        jTextFieldMaLH.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextFieldMaLH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jTextFieldMaLH.setEnabled(false);
        jPanel8.add(jTextFieldMaLH, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 263, 135, 24));

        jLabel11.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel11.setText("Mã lô hàng");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 233, 135, 24));

        jTextField7.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 111, 135, 24));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 507));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 420, 517));

        jLabel17.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Thêm sản phẩm");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 168, 60));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x.png"))); // NOI18N
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 13, 24, 24));

        jDialogAddSP_LH.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 570));

        jDialogUpdateSP_LH.setModal(true);
        jDialogUpdateSP_LH.setUndecorated(true);
        jDialogUpdateSP_LH.setResizable(false);
        jDialogUpdateSP_LH.setSize(new java.awt.Dimension(420, 570));
        jDialogUpdateSP_LH.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(45, 96, 151));
        jPanel9.setMaximumSize(new java.awt.Dimension(420, 568));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(143, 203, 253));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 202, 191)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelUpdate.setBackground(new java.awt.Color(45, 96, 151));
        jPanelUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelUpdateMouseClicked(evt);
            }
        });
        jPanelUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lưu");
        jPanelUpdate.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, -10, 40, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/download.png"))); // NOI18N
        jPanelUpdate.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 8, 24, 24));

        jPanel11.add(jPanelUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 452, 135, 41));

        jLabel16.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel16.setText("Giá");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, 135, 24));

        jLabel19.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel19.setText("Mã sản phẩm");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 135, 24));

        jLabel20.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel20.setText("Mô tả");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 156, 135, 24));

        jLabel21.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel21.setText("Tên sản phẩm");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 22, 135, 24));

        jLabel22.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel22.setText("Phân loại");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 87, 135, 24));

        jLabel23.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel23.setText("Số lượng");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 156, 135, 24));

        jTextFieldMaSP_LH1.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextFieldMaSP_LH1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jTextFieldMaSP_LH1.setEnabled(false);
        jTextFieldMaSP_LH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaSP_LH1ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextFieldMaSP_LH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, 135, 24));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField5.setText("0");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jTextField5.setEnabled(false);
        jPanel11.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 111, 135, 24));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jTextField8.setEnabled(false);
        jPanel11.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 180, 135, 24));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jTextField9.setEnabled(false);
        jPanel11.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 46, 135, 24));

        jTextField10.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField10.setText("0");
        jTextField10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jPanel11.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 180, 135, 24));

        jTextFieldMaLH1.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextFieldMaLH1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jTextFieldMaLH1.setEnabled(false);
        jPanel11.add(jTextFieldMaLH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 263, 135, 24));

        jLabel24.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jLabel24.setText("Mã lô hàng");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 233, 135, 24));

        jTextField11.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 12)); // NOI18N
        jTextField11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(45, 96, 151)));
        jTextField11.setEnabled(false);
        jPanel11.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 111, 135, 24));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 507));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 420, 517));

        jLabel25.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Sửa sản phẩm lô hàng");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 60));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x.png"))); // NOI18N
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 13, 24, 24));

        jDialogUpdateSP_LH.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 570));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(45, 96, 151)));
        setMaximumSize(new java.awt.Dimension(1200, 60));
        setMinimumSize(new java.awt.Dimension(1200, 60));
        setPreferredSize(new java.awt.Dimension(1200, 60));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMaLH.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaLH.setText("Mã LH");
        jLabelMaLH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaLHMouseClicked(evt);
            }
        });
        add(jLabelMaLH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 60));

        jLabelMaNV.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMaNV.setText("Mã NV");
        jLabelMaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaNVMouseClicked(evt);
            }
        });
        add(jLabelMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 170, 60));

        jLabelNgayNhap.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelNgayNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNgayNhap.setText("Ngày nhập");
        jLabelNgayNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNgayNhapMouseClicked(evt);
            }
        });
        add(jLabelNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 150, 60));

        jLabelSuplier.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelSuplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSuplier.setText("Suplier");
        jLabelSuplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSuplierMouseClicked(evt);
            }
        });
        add(jLabelSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 180, 60));

        jLabelSLSP.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelSLSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSLSP.setText("SL SP trong LH");
        jLabelSLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSLSPMouseClicked(evt);
            }
        });
        add(jLabelSLSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 180, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMaLHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaLHMouseClicked
        requestFocus();
    }//GEN-LAST:event_jLabelMaLHMouseClicked

    private void jLabelMaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaNVMouseClicked
        requestFocus();
    }//GEN-LAST:event_jLabelMaNVMouseClicked

    private void jLabelNgayNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNgayNhapMouseClicked
        requestFocus();
    }//GEN-LAST:event_jLabelNgayNhapMouseClicked

    private void jLabelSuplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSuplierMouseClicked
        requestFocus();
    }//GEN-LAST:event_jLabelSuplierMouseClicked

    private void jLabelSLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSLSPMouseClicked
        requestFocus();
    }//GEN-LAST:event_jLabelSLSPMouseClicked

    private void jPanelXoaSP_LHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelXoaSP_LHMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            Object[] rowData = new Object[model.getColumnCount()];
            for (int i = 0; i < model.getColumnCount(); i++) {
                rowData[i] = model.getValueAt(selectedRow, i);
            }
            chiTietKhoDAO.deleteChiTietKho(khoDTO.getMaLoHangString(), rowData[0].toString());
            model.removeRow(selectedRow);
        }
    }//GEN-LAST:event_jPanelXoaSP_LHMouseClicked

    private void jPanelSuaSP_LHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSuaSP_LHMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            Object[] rowData = new Object[model.getColumnCount()];
            for (int i = 0; i < model.getColumnCount(); i++) {
                rowData[i] = model.getValueAt(selectedRow, i);
            }
            SanPhamDAO sanPhamDAO = new SanPhamDAO();
            SanPhamDTO sanPhamDTO = new SanPhamDTO();
            sanPhamDTO = sanPhamDAO.tim(rowData[0].toString());
            jTextFieldMaSP_LH1.setText(sanPhamDTO.getMaSPString());
            jTextField9.setText(sanPhamDTO.getTenSPString());
            jTextField9.setToolTipText(sanPhamDTO.getMaSPString());
            jTextField5.setText(sanPhamDTO.getGiaInt().toString());
            jTextField8.setText(sanPhamDTO.getMoTaString());
            jTextField8.setToolTipText(sanPhamDTO.getMoTaString());
            jTextField11.setText(sanPhamDTO.getPhanLoaiString());
            jTextFieldMaLH1.setText(khoDTO.getMaLoHangString());
            jTextField10.setText(chiTietKhoDAO.tim(khoDTO.getMaLoHangString(), sanPhamDTO.getMaSPString()).getSoLuong().toString());

        }
        jDialogUpdateSP_LH.setVisible(true);
    }//GEN-LAST:event_jPanelSuaSP_LHMouseClicked

    private void jPanelUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelUpdateMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        ChiTietKhoDAO chiTietKhoDAO = new ChiTietKhoDAO();
        chiTietKhoDAO.updateChiTietKho(khoDTO.getMaLoHangString(), jTextFieldMaSP_LH1.getText(), Integer.valueOf(jTextField10.getText()));
        model.setValueAt(jTextField10.getText(), selectedRow, 5);
        jDialogUpdateSP_LH.dispose();
    }//GEN-LAST:event_jPanelUpdateMouseClicked

    private void jTextFieldMaSP_LH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSP_LH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSP_LH1ActionPerformed

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        jDialogUpdateSP_LH.dispose();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jPanelSaveMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelSaveMouseClicked
        // TODO add your handling code here:
        ChiTietKhoDTO chiTietKhoDTO = new ChiTietKhoDTO();
        chiTietKhoDTO.setMaLoHang(jTextFieldMaLH.getText());
        chiTietKhoDTO.setMaSP(jTextFieldMaSP_LH.getText());
        chiTietKhoDTO.setSoLuong(Integer.valueOf(jTextField6.getText()));

        chiTietKhoDAO = new ChiTietKhoDAO();
        try {
            chiTietKhoDAO.insertLoHang(chiTietKhoDTO);
            sanPhamDAO = new SanPhamDAO();
            SanPhamDTO sanPhamDTO = new SanPhamDTO();
            sanPhamDTO = sanPhamDAO.tim(chiTietKhoDTO.getMaSP());
            Object obj[] = new Object[100];
            obj[0] = sanPhamDTO.getMaSPString();
            obj[1] = sanPhamDTO.getTenSPString();
            obj[2] = sanPhamDTO.getPhanLoaiString();
            obj[3] = chiTietKhoDTO.getSoLuong();
            model.addRow(obj);
            jDialogAddSP_LH.dispose();
        } catch (SQLException ex) {
            if (ex.getErrorCode() == -20000) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } else if (ex.getErrorCode() == -21000) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            ex.printStackTrace();
            Logger.getLogger(LoHang_HQT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jPanelSaveMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        jDialogAddSP_LH.dispose();
    }// GEN-LAST:event_jLabel18MouseClicked

    private void jPanelThemSP_LHMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelThemSP_LHMouseClicked
        // TODO add your handling code here:
        jTextFieldMaLH.setText(khoDTO.getMaLoHangString());
        jDialogAddSP_LH.setVisible(true);
    }// GEN-LAST:event_jPanelThemSP_LHMouseClicked

    private void jTextFieldMaSP_LHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldMaSP_LHActionPerformed
        // TODO add your handling code here:
        String maSP = jTextFieldMaSP_LH.getText();
        if (maSP.length() != 0) { // Nếu có nhập ô Mã sản phẩm
            SanPhamBUS sanPhamBUS;
            sanPhamBUS = new SanPhamBUS();
            SanPhamDTO sp = sanPhamBUS.tim(maSP);
            if (sp != null) { // Tìm thấy maSP
                jTextField4.setText(sp.getTenSPString());
                jTextField4.setToolTipText(sp.getMaSPString());
                jTextField2.setText(sp.getGiaInt().toString());
                jTextField3.setText(sp.getMoTaString());
                jTextField3.setToolTipText(sp.getMoTaString());
                jTextField7.setText(sp.getPhanLoaiString());
            } else { // Không tìm thấy maSP
                JOptionPane.showMessageDialog(null, "Không có Mã sản phẩm vừa nhập trong cửa hàng!");
            }
        } else { // Nếu không nhập ô Mã sản phẩm
            jTextField4.setText("");
            jTextField4.setToolTipText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField3.setToolTipText("");
            jTextField7.setText("");
        }
    }// GEN-LAST:event_jTextFieldMaSP_LHActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        isSelect = true;
        setBackground(new java.awt.Color(245, 181, 189));
    }// GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        isSelect = false;
        setBackground(Color.WHITE);
    }// GEN-LAST:event_formFocusLost

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        jDialogDetailLH.dispose();
    }// GEN-LAST:event_jLabel27MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseClicked
        // Double clicked
        long currentTime = System.currentTimeMillis();

        if (clickCount == 1 && (currentTime - lastClickTime) <= 200) {
            // Xử lý sự kiện double click
            System.out.println("Double clicked!");
            chiTietKhoDAO = new ChiTietKhoDAO();
            // Lấy danh sách mã sản phẩm trong lô hàng
            List<String> sanPhamList = new ArrayList<>();
            sanPhamList = chiTietKhoDAO.getSanPhamListByMaLoHang(khoDTO.getMaLoHangString());

            model.setRowCount(0);

            Object obj[] = new Object[100];
            for (int i = 0; i < sanPhamList.size(); i++) {
                sanPhamDAO = new SanPhamDAO();
                obj[0] = sanPhamDAO.tim(sanPhamList.get(i)).getMaSPString();
                obj[1] = sanPhamDAO.tim(sanPhamList.get(i)).getTenSPString();
                obj[2] = sanPhamDAO.tim(sanPhamList.get(i)).getPhanLoaiString();
                obj[3] = chiTietKhoDAO.tim(khoDTO.getMaLoHangString(), sanPhamDAO.tim(sanPhamList.get(i)).getMaSPString()).getSoLuong();
                model.addRow(obj);
            }

            jDialogDetailLH.setVisible(true);
            revalidate();
            repaint();
            // Reset lại số lần click và thời gian sau khi xử lý xong
            clickCount = 0;
            lastClickTime = 0;
        } else {
            // Lưu số lần click và thời gian hiện tại
            clickCount = 1;
            lastClickTime = currentTime;
            requestFocus();
        }
    }// GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialogAddSP_LH;
    private javax.swing.JDialog jDialogDetailLH;
    private javax.swing.JDialog jDialogUpdateSP_LH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMaLH;
    private javax.swing.JLabel jLabelMaNV;
    private javax.swing.JLabel jLabelNgayNhap;
    private javax.swing.JLabel jLabelSLSP;
    private javax.swing.JLabel jLabelSuplier;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelSave;
    private javax.swing.JPanel jPanelSuaSP_LH;
    private javax.swing.JPanel jPanelThemSP_LH;
    private javax.swing.JPanel jPanelUpdate;
    private javax.swing.JPanel jPanelXoaSP_LH;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldMaLH;
    private javax.swing.JTextField jTextFieldMaLH1;
    private javax.swing.JTextField jTextFieldMaSP_LH;
    private javax.swing.JTextField jTextFieldMaSP_LH1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the isSelect
     */
    public boolean isSelect() {
        return isSelect;
    }

    /**
     * @param isSelect the isSelect to set
     */
    public void setIsSelect(boolean isSelect) {
        this.isSelect = isSelect;
    }

    /**
     * @return the khoDTO
     */
    public KhoDTO getKhoDTO() {
        return khoDTO;
    }

    /**
     * @param khoDTO the khoDTO to set
     */
    public void setKhoDTO(KhoDTO khoDTO) {
        this.khoDTO = khoDTO;
    }
}
