/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO_Hibernate.SanPhamDAO;
import DTO.ChiTietHoaDonDTO;
import DTO.SanPhamDTO;

/**
 *
 * @author Locc
 */
public class CTHD extends javax.swing.JPanel {

    private ChiTietHoaDonDTO chiTietHoaDonDTO;
    private SanPhamDAO sanPhamDAO;
    private SanPhamDTO sanPhamDTO;

    /**
     * Creates new form CTHD
     */
    public CTHD() {
        initComponents();
    }

    public CTHD(ChiTietHoaDonDTO chiTietHoaDonDTO) {
        initComponents();
        this.chiTietHoaDonDTO = new ChiTietHoaDonDTO();
        this.sanPhamDAO = new SanPhamDAO();
        this.sanPhamDTO = new SanPhamDTO();

        this.chiTietHoaDonDTO = chiTietHoaDonDTO;
        sanPhamDTO = sanPhamDAO.tim(this.chiTietHoaDonDTO.getMaSP());
        jLabelTenSP.setText(sanPhamDTO.getTenSPString());
        jLabelGia.setText(sanPhamDTO.getGiaInt().toString());
        jLabelSL.setText(this.chiTietHoaDonDTO.getSoLuong().toString());
        jLabelThanhTien.setText(this.chiTietHoaDonDTO.getGia().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTenSP = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jLabelSL = new javax.swing.JLabel();
        jLabelThanhTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(670, 40));
        setMinimumSize(new java.awt.Dimension(670, 40));
        setPreferredSize(new java.awt.Dimension(670, 40));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTenSP.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabelTenSP.setText("TenSP");
        add(jLabelTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 340, 40));

        jLabelGia.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabelGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGia.setText("Giá");
        add(jLabelGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 130, 40));

        jLabelSL.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabelSL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSL.setText("SL");
        add(jLabelSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 60, 40));

        jLabelThanhTien.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabelThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelThanhTien.setText("Thành tiền");
        add(jLabelThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 145, 40));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelSL;
    private javax.swing.JLabel jLabelTenSP;
    private javax.swing.JLabel jLabelThanhTien;
    // End of variables declaration//GEN-END:variables
}
