/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO_Hibernate.ChiTietKhoDAO;
import DTO.ChiTietKhoDTO;
import DTO.SanPhamDTO;
import static GUI.LoHang.formatter;
import java.awt.Color;

/**
 *
 * @author Locc
 */
public class CTKho extends javax.swing.JPanel {

    private boolean isSelect;

    /**
     * Creates new form CTKho
     */
    public CTKho() {
        initComponents();
    }

    public CTKho(String maLoHang, SanPhamDTO sanPhamDTO) {
        initComponents();
        jLabelMaSP.setText(sanPhamDTO.getMaSPString());
        jLabelTenSP.setText(sanPhamDTO.getTenSPString());
        jLabelTenSP.setToolTipText(sanPhamDTO.getTenSPString());
        jLabelPhanLoai.setText(sanPhamDTO.getPhanLoaiString());
        jLabelPhanLoai.setToolTipText(sanPhamDTO.getPhanLoaiString());
//        jLabelNSX.setText(formatter.format(sanPhamDTO.getNSXDate()));
//        jLabelHSD.setText(formatter.format(sanPhamDTO.getHSDDate()));
        ChiTietKhoDAO chiTietKhoDAO = new ChiTietKhoDAO();
        ChiTietKhoDTO chiTietKhoDTO = chiTietKhoDAO.tim(maLoHang, sanPhamDTO.getMaSPString());
        jLabelSoLuong.setText(chiTietKhoDTO.getSoLuong().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTenSP = new javax.swing.JLabel();
        jLabelMaSP = new javax.swing.JLabel();
        jLabelPhanLoai = new javax.swing.JLabel();
        jLabelSoLuong = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1148, 60));
        setMinimumSize(new java.awt.Dimension(1148, 60));
        setPreferredSize(new java.awt.Dimension(1148, 60));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTenSP.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelTenSP.setText("Tên sản phẩm");
        jLabelTenSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTenSPMouseClicked(evt);
            }
        });
        add(jLabelTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 297, 60));

        jLabelMaSP.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaSP.setText("SP001");
        jLabelMaSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMaSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaSPMouseClicked(evt);
            }
        });
        add(jLabelMaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 60));

        jLabelPhanLoai.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelPhanLoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPhanLoai.setText("Phân loại");
        jLabelPhanLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPhanLoaiMouseClicked(evt);
            }
        });
        add(jLabelPhanLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 180, 60));

        jLabelSoLuong.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSoLuong.setText("SL");
        jLabelSoLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSoLuongMouseClicked(evt);
            }
        });
        add(jLabelSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 132, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        setBackground(new java.awt.Color(245, 181, 189));
        isSelect = true;
        System.out.println(isSelect);
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        isSelect = false;
        setBackground(Color.WHITE);
        System.out.println(isSelect);
    }//GEN-LAST:event_formFocusLost

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_formMouseClicked

    private void jLabelMaSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaSPMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_jLabelMaSPMouseClicked

    private void jLabelTenSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTenSPMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_jLabelTenSPMouseClicked

    private void jLabelPhanLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPhanLoaiMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_jLabelPhanLoaiMouseClicked

    private void jLabelSoLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSoLuongMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_jLabelSoLuongMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMaSP;
    private javax.swing.JLabel jLabelPhanLoai;
    private javax.swing.JLabel jLabelSoLuong;
    private javax.swing.JLabel jLabelTenSP;
    // End of variables declaration//GEN-END:variables
    /**
     * @return the isSelect
     */
    public boolean isSelect() {
        return isSelect;
    }

    /**
     * @param isSelect the isSelect to set
     */
    public void setIsSelect(boolean isSelect) {
        this.isSelect = isSelect;
    }
}
