/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO_Hibernate.ChiTietHoaDonDAO;
import DAO_Hibernate.KhachHangDAO;
import DTO.ChiTietHoaDonDTO;
import DTO.HoaDonDTO;
import DTO.KhachHangDTO;
import static GUI.LoHang.formatter;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Locc
 */
public class Invoice extends javax.swing.JPanel {

    private boolean isSelect;

    private int clickCount;
    private long lastClickTime;

    private HoaDonDTO hoaDonDTO;
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
    }

    public Invoice(HoaDonDTO hoaDonDTO) {
        initComponents();
        jDialog1.setLocationRelativeTo(null);
        this.hoaDonDTO = new HoaDonDTO();
        this.hoaDonDTO = hoaDonDTO;
        jLabelMaHD.setText(hoaDonDTO.getMaHDString());

        jLabelNgayLap.setText(dateFormat.format(hoaDonDTO.getNgayMuaHangHDDate()));
        jLabelMaNV.setText(hoaDonDTO.getMaNVString());
        jLabelMaKH.setText(hoaDonDTO.getMaKHString());
        jLabelHTTT.setText(hoaDonDTO.getHinhThucThanhToanHDString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMaHD = new javax.swing.JLabel();
        jLabelNgayLap = new javax.swing.JLabel();
        jLabelMaNV = new javax.swing.JLabel();
        jLabelMaKH = new javax.swing.JLabel();
        jLabelHTTT = new javax.swing.JLabel();

        jDialog1.setBackground(new java.awt.Color(45, 96, 151));
        jDialog1.setMinimumSize(new java.awt.Dimension(700, 800));
        jDialog1.setModal(true);
        jDialog1.setUndecorated(true);
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(580, 800));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 96, 151));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 800));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(143, 203, 253));
        jPanel2.setMaximumSize(new java.awt.Dimension(700, 734));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 734));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 734));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel2.setText("Mã đơn hàng:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 130, 30));

        jLabel13.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel13.setText("01/01/2023");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 41, 410, 30));

        jLabel3.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel3.setText("Ngày:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 41, 60, 30));

        jLabel4.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel4.setText("Nhân viên:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 71, 100, 30));

        jLabel5.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel5.setText("Khách hàng:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 101, 120, 30));

        jLabel6.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel6.setText("Tổng Tiền:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 694, 110, 40));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("0");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 160, 40));

        jPanel2.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 694, 190, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(670, 540));
        jPanel3.setMinimumSize(new java.awt.Dimension(670, 540));
        jPanel3.setPreferredSize(new java.awt.Dimension(670, 540));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel8.setText("Sản Phẩm");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 190, 40));

        jLabel9.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Giá");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 120, 40));

        jLabel10.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SL");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 60, 40));

        jLabel11.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thành Tiền");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 140, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel5);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, 500));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 670, 540));

        jLabel14.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel14.setText("NV000x");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 71, 390, 30));

        jLabel15.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 101, 520, 30));

        jLabel12.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 18)); // NOI18N
        jLabel12.setText("HDxxx");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 11, 360, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 750));

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x.png"))); // NOI18N
        jLabel43.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 13, 24, 24));

        jLabel1.setFont(new java.awt.Font("Be Vietnam Pro SemiBold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi tiết hóa đơn");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        jDialog1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 800));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(45, 96, 151)));
        setMaximumSize(new java.awt.Dimension(1200, 60));
        setMinimumSize(new java.awt.Dimension(1200, 60));
        setPreferredSize(new java.awt.Dimension(1200, 60));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMaHD.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaHD.setText("HD00000X");
        jLabelMaHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaHDMouseClicked(evt);
            }
        });
        add(jLabelMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 160, 50));

        jLabelNgayLap.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelNgayLap.setText("01/01/2023");
        jLabelNgayLap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNgayLapMouseClicked(evt);
            }
        });
        add(jLabelNgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 5, 290, 50));

        jLabelMaNV.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaNV.setText("NV00000X");
        jLabelMaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaNVMouseClicked(evt);
            }
        });
        add(jLabelMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 5, 140, 50));

        jLabelMaKH.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelMaKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMaKH.setText("KH000001");
        jLabelMaKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaKHMouseClicked(evt);
            }
        });
        add(jLabelMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 5, 170, 50));

        jLabelHTTT.setFont(new java.awt.Font("Be Vietnam Pro Light", 0, 24)); // NOI18N
        jLabelHTTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHTTT.setText("HTTT");
        jLabelHTTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHTTTMouseClicked(evt);
            }
        });
        add(jLabelHTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 5, 180, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        // TODO add your handling code here:
        jDialog1.dispose();
    }//GEN-LAST:event_jLabel43MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        // double clicked
        long currentTime = System.currentTimeMillis();

        if (clickCount == 1 && (currentTime - lastClickTime) <= 200) {
            // Xử lý sự kiện double click
            ChiTietHoaDonDAO chiTietHoaDonDAO = new ChiTietHoaDonDAO();
            List<ChiTietHoaDonDTO> chiTietHoaDonDTOs = new ArrayList<>();
            chiTietHoaDonDTOs = chiTietHoaDonDAO.tim(hoaDonDTO.getMaHDString());
            jPanel5.removeAll();
            for (int i = 0; i < chiTietHoaDonDTOs.size(); i++) {
                CTHD cthd = new CTHD(chiTietHoaDonDTOs.get(i));
                jPanel5.add(cthd);
            }
            jLabel12.setText(hoaDonDTO.getMaHDString());
            jLabel13.setText(dateFormat.format(hoaDonDTO.getNgayMuaHangHDDate()));
            jLabel14.setText(hoaDonDTO.getMaNVString());
            // Tìm tên khách hàng
            KhachHangDAO khachHangDAO = new KhachHangDAO();
            KhachHangDTO khachHangDTO = new KhachHangDTO();
            khachHangDTO = khachHangDAO.tim(hoaDonDTO.getMaKHString());
            if (khachHangDTO != null) {
                jLabel15.setText(khachHangDTO.gettenKHString());
            }

            jLabel7.setText(hoaDonDTO.getTriGiaHDInteger().toString());
            jPanel5.revalidate();
            jPanel5.repaint();
            jDialog1.setVisible(true);
//            System.out.println("Double clicked!");

            // Reset lại số lần click và thời gian sau khi xử lý xong
            clickCount = 0;
            lastClickTime = 0;
        } else {
            // Lưu số lần click và thời gian hiện tại
            requestFocus();
            clickCount = 1;
            lastClickTime = currentTime;
        }

    }//GEN-LAST:event_formMouseClicked

    private void jLabelMaHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaHDMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_jLabelMaHDMouseClicked

    private void jLabelNgayLapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNgayLapMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_jLabelNgayLapMouseClicked

    private void jLabelMaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaNVMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_jLabelMaNVMouseClicked

    private void jLabelMaKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaKHMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_jLabelMaKHMouseClicked

    private void jLabelHTTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHTTTMouseClicked
        // TODO add your handling code here:
        requestFocus();
    }//GEN-LAST:event_jLabelHTTTMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        setBackground(new java.awt.Color(245, 181, 189));
        isSelect = true;
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        setBackground(Color.WHITE);
        isSelect = false;
    }//GEN-LAST:event_formFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHTTT;
    private javax.swing.JLabel jLabelMaHD;
    private javax.swing.JLabel jLabelMaKH;
    private javax.swing.JLabel jLabelMaNV;
    private javax.swing.JLabel jLabelNgayLap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
    /**
     * @return the isSelect
     */
    public boolean isSelect() {
        return isSelect;
    }

    /**
     * @param isSelect the isSelect to set
     */
    public void setSelect(boolean isSelect) {
        this.isSelect = isSelect;
    }
}
